name: mytutor
description: Tutor finding application with Flutter



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  smooth_page_indicator: ^0.2.0
  provider: ^4.3.3
  font_awesome_flutter: ^8.11.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  shared_preferences: ^0.5.12+4
  animated_text_kit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
     - images/
     - images/TourScreen/
     - images/Roles/
     - images/Sub-Icons/
     - images/Login/
     - images/Student_Section/
     - images/Tutor_Section/
